-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("Print")
hl.bind("Print", hl.dsp.exec_cmd("dms screenshot"), { description = "Screenshot: Region" })
hl.unbind("SUPER + H")
hl.bind("SUPER + H", hl.dsp.exec_cmd("dms ipc call island close"), { description = "DankIsland: Close" })
hl.unbind("SUPER + I")
hl.bind("SUPER + I", hl.dsp.exec_cmd("dms ipc call inhibit toggle"), { description = "Idle Inhibit: Toggle" })
hl.unbind("SUPER + L")
hl.bind("SUPER + L", hl.dsp.exec_cmd("dms ipc call lock lock"), { description = "Lock Screen" })
hl.unbind("SUPER + P")
hl.bind("SUPER + P", hl.dsp.exec_cmd("dms ipc call powermenu open"), { description = "Power Menu: Open" })
hl.unbind("XF86AudioLowerVolume")
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call audio decrement 1"), { description = "Volume Down (1%)" })
hl.unbind("XF86AudioMute")
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("dms ipc call audio mute"), { description = "Volume Mute Toggle" })
hl.unbind("XF86AudioNext")
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("dms ipc call mpris next"), { description = "Media: Next Track" })
hl.unbind("XF86AudioPlay")
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("dms ipc call mpris playPause"), { description = "Media: Play/Pause" })
hl.unbind("XF86AudioPrev")
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("dms ipc call mpris previous"), { description = "Media: Previous Track" })
hl.unbind("XF86AudioRaiseVolume")
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call audio increment 1"), { description = "Volume Up (1%)" })
hl.unbind("SUPER + T")
hl.unbind("XF86AudioPause")
