-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "DP-1", mode = "3440x1440@164.999", position = "0x480", scale = 1, vrr = 0 })
hl.monitor({ output = "DP-2", mode = "1920x1080@164.955", position = "3440x0", scale = 1, transform = 3, vrr = 0 })
