# Path of Exile
# windowrulev2=tag +poe, title:(Path of Exile)
# windowrulev2=tag +poe, class:(steam_app_238960)
# windowrulev2=fullscreen, tag:poe

# awakened PoE Trade
windowrule {
  name = tag-apt
  tag = +apt
  match:title = (Awakened PoE Trade)
}

windowrule {
  name = apt-1
  float = on
  no_blur = on
  no_shadow = on
  border_size = 0
  pin = on
  render_unfocused = on
  size = (monitor_w*1) (monitor_h*1)
  center = on
  match:tag = apt
}

windowrule {
  name = apt-2
  no_focus = on
  match:tag = apt # Disable auto-focus
}


# inhibit hyprdile on fullscreen apps
windowrule {
  name = idle-inhibit
  idle_inhibit = fullscreen
  suppress_event = maximize
  match:class = .*
}


# force tiling for certain apps
windowrule {
  name = tile-battlenet
  tile = on
  match:title = (Battle.net)
}

windowrule {
  name = tile-battlenet-chats
  tile = on
  match:title = (Battle.net - Chats and Groups)
}

windowrule {
  name = tile-vivaldi-settings
  tile = on
  match:title = (Vivaldi Settings:.*)
}


windowrule {
  name = tile-pob
  tile = on
  match:title = (.*Path of Building)
}


# default
windowrule {
  name = defaults
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}
