# Only execute this file once per shell.
set -q __fish_config_sourced; and exit
set -g __fish_config_sourced 1

setup_session_vars

fish_config theme choose "Catppuccin Mocha"
setup_vim-key-binds

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # configure eza
    setup_eza

    # configure lazygit
    setup_lazygit

    # configure lazyjj
    setup_lazyjj

    # configure fzf
    setup_fzf

    # configure zoxide
    setup_zoxide

    # configure starship
    setup_starship

    # configure pay-respects
    setup_pay-respects

    # configure yazi
    setup_yazi

    # configure kitty shell integration
    setup_kitty

    # Abbreviations

    # TODO check if this is sill needed
    # from home manager, don't know what to do with these yet
    #
    # add completions generated by Home Manager to $fish_complete_path
    # begin
    #     set -l joined (string join " " $fish_complete_path)
    #     set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
    #     set -l post_joined (string replace $prev_joined "" $joined)
    #     set -l prev (string split " " (string trim $prev_joined))
    #     set -l post (string split " " (string trim $post_joined))
    #     set fish_complete_path $prev "/home/tamel/.local/share/fish/home-manager_generated_completions" $post
    # end

    # configure carapace
    setup_carapace

end
